In [ ]:
## for data
import pandas as pd
import numpy as np

## for plotting
import matplotlib.pyplot as plt
import seaborn as sns

## for statistical tests
import scipy

## for machine learning
from sklearn import model_selection, preprocessing, feature_selection, ensemble, linear_model, metrics, decomposition
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, recall_score, precision_score
from sklearn.svm import SVC
from sklearn import datasets
import matplotlib.cm as cm

#dataset
from sklearn.datasets import load_wine

In [ ]:
wine = load_wine()

In [ ]:
x = wine.data
y = wine.target

In [ ]:
targets = wine.target
#print(targets)
n_targets = len(targets)
features = wine.feature_names
n_features = len(features)
print(n_targets)

178


In [ ]:
from sklearn.preprocessing import LabelEncoder

# Matriz de etiquetas en formato de text

# Crear una instancia de LabelEncoder
label_encoder = LabelEncoder()

# Ajustar el codificador a las etiquetas de texto
label_encoder.fit(y)

# Transformar las etiquetas de texto a etiquetas numéricas
etiquetas_numericas = label_encoder.transform(y)

# Imprimir las etiquetas numéricas
print(len(etiquetas_numericas))

178


Neurona Perceptron

In [ ]:
def perceptron(x, w):
  ws = sum(x*w)
  yt = 0
  if ws < 0:
    yt = -1
  elif ws > 0:
    yt = 1

  return yt

Función Multi-perceptrón

In [ ]:
def perceptron_multi(x, w):
  yp = []
  for xi in x:
    yp.append(perceptron(xi, w))
  return np.array(yp)

In [ ]:
from keras.utils import np_utils
output_y = np_utils.to_categorical(y)
print(output_y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [ ]:
#Define MLP model
from keras.models import Sequential
from keras.layers import Dense
from keras.regularizers import l2

clf = Sequential()
clf.add(Dense(20, input_dim = n_features, activation = 'relu',kernel_regularizer=l2(100)))
clf.add(Dense(20, activation = 'relu',kernel_regularizer=l2(100)))
clf.add(Dense(20, activation = 'relu', kernel_regularizer=l2(100)))
clf.add(Dense(20, activation = 'relu', kernel_regularizer=l2(100)))
clf.add(Dense(20, activation = 'relu', kernel_regularizer=l2(100)))

clf.add(Dense(3, activation = 'softmax'))

In [ ]:
#Compile model
clf.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

#Fit model
clf.fit(x, output_y, epochs = 100, batch_size = 15)

Epoch 1/100
12/12 [==============================] - 2s 3ms/step - loss: 9198.9629 - accuracy: 0.3034
Epoch 2/100
12/12 [==============================] - 0s 3ms/step - loss: 8374.1670 - accuracy: 0.2753
Epoch 3/100
12/12 [==============================] - 0s 3ms/step - loss: 7613.0718 - accuracy: 0.2753
Epoch 4/100
12/12 [==============================] - 0s 3ms/step - loss: 6915.3750 - accuracy: 0.2303
Epoch 5/100
12/12 [==============================] - 0s 3ms/step - loss: 6277.1221 - accuracy: 0.2697
Epoch 6/100
12/12 [==============================] - 0s 3ms/step - loss: 5693.8354 - accuracy: 0.2697
Epoch 7/100
12/12 [==============================] - 0s 3ms/step - loss: 5160.8599 - accuracy: 0.2697
Epoch 8/100
12/12 [==============================] - 0s 3ms/step - loss: 4673.9106 - accuracy: 0.2753
Epoch 9/100
12/12 [==============================] - 0s 3ms/step - loss: 4229.1470 - accuracy: 0.2921
Epoch 10/100
12/12 [==============================] - 0s 3ms/step - loss: 3823.118

Cross-Validation con tres clases


In [ ]:
# Evaluate model
from sklearn.model_selection import StratifiedKFold
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

kf = StratifiedKFold(n_splits=5, shuffle = True)
acc = 0
recall = np.array([0., 0., 0.])

for train_index, test_index in kf.split(x,y):

  # Training phase
  x_train, x_val = x[train_index], x[test_index]
  y_train, y_val = y[train_index], y[test_index]

  clf_cv = Sequential()
  clf_cv.add(Dense(20, input_dim=n_features, activation='relu'))
  clf_cv.add(Dense(20, activation='relu'))
  clf_cv.add(Dense(20, activation='relu'))
  clf_cv.add(Dense(20, activation='relu'))
  clf_cv.add(Dense(20, activation='relu'))

  clf_cv.add(Dense(3, activation='softmax'))
  clf_cv.compile(loss='categorical_crossentropy', optimizer='adam')

  y_train_encoded = np_utils.to_categorical(y_train)
  y_val_encoded = np_utils.to_categorical(y_val)

  clf_cv.fit(x_train, y_train_encoded, epochs=150, batch_size=15, verbose=0, validation_data=(x_val, y_val_encoded))

  # Test phase
  y_pred = np.argmax(clf_cv.predict(x_val), axis=1)

  # Performance scores
  acc += accuracy_score(y_val, y_pred)

acc = acc/5
print('ACC = ', acc)

2/2 [==============================] - 0s 7ms/step
ACC =  0.9326984126984128
